#ifndef PARSER_H
#define PARSER_H


typedef enum _PARSER_STATE_T {
    PARSER_LOOKING_FOR_START = 0,
    PARSER_LOOKING_FOR_CMD,
    PARSER_LOOKING_FOR_LEN,
    PARSER_LOOKING_FOR_DATA,
    PARSER_LOOKING_FOR_END
} PARSER_STATE_T;


char* Parser_AddChar(char new_char);


#endif //PARSER_H
